### ISSUE TITLE
Write analysis for practice exercise `accumulate`

### ISSUE THREAD

**Issue by jiegillet** [exercism/elm-analyzer#24]
The exercise description says:

> Restrictions
> Keep your hands off that collect/map/fmap/whatchamacallit functionality provided by your standard library! Solve this one yourself using other basic tools instead.

The exercise can be solved with `accumulate = List.map` but should avoid the use of any `List` functions and promote implementing it with pattern matching and recursion instead. The example solution should also be changed accordingly.

**Comment by jiegillet** [comment]
This exercise has been [deprecated](https://github.com/exercism/problem-specifications/blob/main/exercises/accumulate/.deprecated), not worth adding an analysis for.
The advice is to implement `list-ops` instead, which we have.
@ceddlyburge do you think we should remove the exercise or not worry about it and leave it? AFAIK it's the track's choice.

**Comment by mpizenberg** [comment]
For what its worth, I personally do not like the accumulate exercise, and very much prefer the list-ops one. (just my 2 cents)

**Comment by ceddlyburge** [comment]
I agree, the list-ops one is better, and as you mention, this one is deprecated, so probably removing it is best. There are about 100 published solutions of it, so those people will lose those solutions, but I don't think that is a huge deal. Those people will almost certainly have done other solutions as well, so probably won't really notice.
