### ISSUE TITLE
Write analysis for concept exercise Top Scorers

### ISSUE THREAD

**Issue by ceddlyburge** [exercism/elm-analyzer#34]
Checks to be as follows

- filter must be used in removeInsignificantPlayers
- insert must be used in resetPlayerCounts
- sort must not be used in formatPlayers
- updateGoalCountForPlayer and List.foldl must be used in aggregateScorers
- Maybe.map and Maybe.withDefault should be used in formatPlayer
- merge must be used in combineGames

**Comment by jiegillet** [comment]
Closed via #36
