### ISSUE TITLE
code review of Bandwagoner suggests two conflicting 

### ISSUE THREAD

**Issue by ojob** [exercism/elm-analyzer#75]
In the [Bandwagoner exercise](https://exercism.org/tracks/elm/exercises/bandwagoner/edit), considering the function type annotation requires fields `stats.wins` and `stats.losses` to exist, I wrote the following code:

```elm
rootForTeam: {a|stats: {wins: Int, losses: Int}} -> Bool
rootForTeam team =
    let {wins, losses} = team.stats
    in wins > losses
```

This code passes the tests, however, at code review, I get the following message:

> *Essential*
>
> Like the instructions mention, you should use pattern matching to get stats from the function parameter in rootForTeam.

So, new trial with a pattern match, i.e. with the following code:

```elm
rootForTeam: {a|stats: {wins: Int, losses: Int}} -> Bool
rootForTeam team =
    case team.stats of
        {wins, losses} -> wins > losses
```

then I get the following message:

> *Essential*
>
> Like the instructions mention, you should use pattern matching to get stats from the function parameter in rootForTeam.
>
> *Recommended*
>
> A way to simplify your code has been found.
>
> Simplify: Use a let expression to destructure data
> 
> ```elm
> 27|     case team.stats of
> 28|         {wins, losses} -> wins > losses
>             ^^^^^^^^^^^^^^
> ```
>
> It is more idiomatic in Elm to use a let expression to define a new variable rather than to use pattern matching. This will also make the code less indented, therefore easier to read.

---

I understand the recommandation, as using `let` was in fact my first bet.

But what about the essential message, as I now use the pattern match? Isn't this a false error?

Thanks for your feedback, and for Exercism!

**Comment by mpizenberg** [comment]
Hi @ojob I think it's a misuse of language in the reported error. The exact term is not "pattern matching" but "destructuring". So you should "destructure" the function argument directly : 
```elm
rootForTeam: {a|stats: {wins: Int, losses: Int}} -> Bool
rootForTeam { stats } = ... -- see how the record argument itself is destructured to extract "stats"
```

**Comment by jiegillet** [comment]
Thanks for opening an issue @ojob, it's a brand new rule of the analyzer and we welcome feedback very much.
It's exactly as @mpizenberg said. We will rework the analyzer message. What would you think of:

> Like the instructions mention, you should extract `stats` directly from the argument of `rootForTeam` using destructuring.

**Comment by ojob** [comment]
Ahah, OK nice! Got it.

@jiegillet From my knowledge of Elm, this seems sufficiently specific, while still letting some exercise to the user. Searching for `elm destructuring` gives some hints but no direct answer thought, which ensure homework to be completed!

Thanks for the quick feedback!

**Comment by jiegillet** [comment]
There is a dedicated concept for pattern matching and destructuring later in the tree. Maybe we shouldn't use this rule at this point at all?

**Comment by ceddlyburge** [comment]
I think that makes sense. Or we could make it a lower level comment and mention that it will be taught later, but I think just not having the rule is better,
